# Generated by Django 3.2.9 on 2022-08-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
"""
CREATE TABLE "user" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(512) NOT NULL UNIQUE,
    password VARCHAR(512) NOT NULL
);

CREATE TABLE user_settings (
    id INTEGER PRIMARY KEY,
    setting TEXT
);

CREATE TABLE role (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE dash (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    body TEXT,
    modified TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE permission (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "group" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    color VARCHAR(100) NOT NULL
);

CREATE TABLE index (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE session (
    id SERIAL PRIMARY KEY,
    token TEXT UNIQUE,
    user_id INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    expired_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE user_role (
    user_id INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    role_id INT NOT NULL REFERENCES role(id) ON DELETE CASCADE,
    CONSTRAINT user_role_id UNIQUE(user_id, role_id)
);

CREATE TABLE index_group (
    index_id INT NOT NULL REFERENCES index(id) ON DELETE CASCADE,
    group_id INT NOT NULL REFERENCES "group"(id) ON DELETE CASCADE,
    CONSTRAINT index_group_id UNIQUE(index_id, group_id)
);

CREATE TABLE user_group (
    user_id INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    group_id INT NOT NULL REFERENCES "group"(id) ON DELETE CASCADE,
    CONSTRAINT user_group_id UNIQUE(user_id, group_id)
);

CREATE TABLE dash_group (
    dash_id INT NOT NULL REFERENCES dash(id) ON DELETE CASCADE,
    group_id INT NOT NULL REFERENCES "group"(id) ON DELETE CASCADE,
    CONSTRAINT dash_group_id UNIQUE(dash_id, group_id)
);

CREATE TABLE role_permission (
    permission_id INT NOT NULL REFERENCES permission(id) ON DELETE CASCADE,
    role_id INT NOT NULL REFERENCES role(id) ON DELETE CASCADE,
    value BOOLEAN,
    CONSTRAINT role_permission_id UNIQUE(permission_id, role_id)
);

CREATE TABLE theme (
    name VARCHAR (256) PRIMARY KEY,
    content TEXT
);
"""
                          ),
        migrations.RunSQL(
"""
INSERT INTO "user" (name, password) VALUES ('admin', '$2b$12$ODxOO2wd6vRy2wT4euCJxeKPwU7.GW7HvTrcFmCQgTFbMQOfj851e');
INSERT INTO permission (name) VALUES ('admin_all');
INSERT INTO role (name) VALUES ('admin');
INSERT INTO user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO index (name) VALUES ('*');
INSERT INTO "group" (id, name, color) VALUES (1, 'DefaultGroup', '#ACE90CFF');
INSERT INTO index_group VALUES (1, 1);
INSERT INTO role_permission (role_id, permission_id) VALUES (1, 1);
"""
        ),
        migrations.RunSQL(
"""
-- ###### QUIZ ######
CREATE TYPE multi_str AS ENUM ('yes', 'no', 'skip');

CREATE TABLE quiz (
    id SERIAL PRIMARY KEY,
    name VARCHAR(512) NOT NULL
);

CREATE TABLE filled_quiz (
    id SERIAL PRIMARY KEY,
    quiz_id INT REFERENCES quiz(id) ON DELETE CASCADE,
    filler VARCHAR(256),
    fill_date timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE catalog (
    id SERIAL PRIMARY KEY,
    name VARCHAR (256),
    content TEXT
);

CREATE TABLE question (
    id SERIAL PRIMARY KEY,
    description TEXT,
    quiz_id INT REFERENCES quiz(id) ON DELETE CASCADE,
    sid INT,
    text TEXT NOT NULL,
    type VARCHAR(100) NOT NULL,
    is_sign BOOLEAN DEFAULT FALSE,
    label VARCHAR(256),
    parent_id INT REFERENCES question(id) ON DELETE CASCADE,
    catalog_id INT REFERENCES catalog(id) ON DELETE CASCADE
);

CREATE TABLE boolAnswer (
    id INT NOT NULL REFERENCES filled_quiz(id) ON DELETE CASCADE,
    sid INT NOT NULL,
    value BOOLEAN,
    description TEXT
);

CREATE TABLE multiAnswer (
    id INT NOT NULL REFERENCES filled_quiz(id) ON DELETE CASCADE,
    sid INT NOT NULL,
    value multi_str,
    description TEXT
);

CREATE TABLE textAnswer (
    id INT NOT NULL REFERENCES filled_quiz(id) ON DELETE CASCADE,
    sid INT NOT NULL,
    value TEXT,
    description TEXT
);

CREATE TABLE dateAnswer(
    id INT NOT NULL REFERENCES filled_quiz(id) ON DELETE CASCADE,
    sid INT NOT NULL,
    value timestamptz DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);

CREATE TABLE cascadeAnswer(
    id INT NOT NULL REFERENCES filled_quiz(id) ON DELETE CASCADE,
    sid INT NOT NULL,
    value TEXT,
    description TEXT
);

CREATE TABLE catalogAnswer(
    id INT NOT NULL REFERENCES filled_quiz(id) ON DELETE CASCADE,
    sid INT NOT NULL,
    value TEXT,
    description TEXT
);

"""
        )
    ]
